version: '3.8'

services:

  app:
    build:
      context: ..
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=pgdb
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pgdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: